dist: trusty
sudo: false
language: python
python:
- '3.5'
branches:
  only:
  - master
install:
- pip install -r requirements.txt
script:
- python manage.py makemigrations
- python manage.py migrate
deploy:
  provider: heroku
  api_key:
    secure: VzwpCKn/erfSzMOgPZ1xRfgpXgvASFIRKBmyv9M3XAsnEvVOJhhy0AIAPBbpouvxvCyvjCELiipbvMw4R1VGXB8uPxBXd4iRw7c1ejFLjgsxQHBgtDRm9QfmDAHzCZfyIcukH0g45uPGSmfX+lhOXqSzY70xbiC89kpFUiT4robVUzPHmsza79I95MyuXSxv4f18MGFr99Uxs8ENJC4nSxgCYAZjzmNQ4MtrbdkLP7QrbXzr0Hbh+efmJKt0qiBFRwRWKD0KxxQMC7WTLqdKans0doClly0D9PY5qyjPdt9pKUcvP0mP6sMKhtEzbH0U7jlF0gI8Gs+lhKz11abiKQRTr6o4ypklfHmvszUIPgP/jXiALOpkXdgFn6RciG16R9O06BkhaUo+jpf2qDn9OB+OtC5d+ES2pUB9bpL9fNe2iisk9EWG6xkuCEy0iyMgCeu4HLDRTTCDWVxQx6f6GiteJ1E7O3a3lVqSlDyqBSzz5D/MJWleVNEDk2RDeaFsf/azJqJ//v+bCAjscb2G010kqtlKcLtxrXEzeyooO4HF42jaHMTaPxxE2SzAicCx+rUqB/w05NEfEy9CGuDrtWoIDR1YeIRbUgyi9STsomuLuiEPhDfGtwk5Qb8hDzQ6FhMSLoSa27+hIzi6VLbx3DJ1HZ723Aw7Z+NrU74tN+s=
  app: sdro-cbmes
  on:
    repo: heitorbc/sdro-cbmes
