dist: trusty
sudo: false
language: python
python:
- '3.5'
branches:
  only:
  - master
install:
  - pip install -r requirements.txt
script:
  - python manage.py makemigrations
  - python manage.py migrate